name: My Workflow

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test_job:
    uses: ./.github/workflows/test_sub.yml
    with:
      environment: 'qa'
