name: My Workflow

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A job to test my tests running
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run My Custom Action
        uses: ./.github/workflows/tests/action.yml
        with:
          environment: 'qa'
