name: My Workflow

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A job to test my tests running
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run tests 
        uses: ./.github/workflows/tests/test_sub.yml@main
        with:
            environment: 'qa'
